spring:
  application:
    name: voxticket

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/voxticket2.0}
    username: ${DB_USERNAME:muzammil}
    password: ${DB_PASSWORD:6346}

  flyway:
    enabled: true

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus

voxticket:
  commerce:
    returns:
      window-days: 30