package com.voxticket.api.chat;

import static org.assertj.core.api.Assertions.assertThat;

import com.voxticket.persistence.entity.Customer;
import com.voxticket.persistence.repository.CustomerRepository;
import java.util.UUID;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.testcontainers.service.connection.ServiceConnection;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.transaction.annotation.Transactional;
import org.testcontainers.containers.PostgreSQLContainer;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;

/** Phase 4 acceptance test: chat exercises the real shared runtime end-to-end without going through voice. */
@Testcontainers
@ActiveProfiles("test")
@SpringBootTest
@Transactional
class ChatControllerIntegrationTest {

    @Container
    @ServiceConnection
    static final PostgreSQLContainer<?> POSTGRES = new PostgreSQLContainer<>("postgres:16-alpine");

    @Autowired
    private ChatController chatController;
    @Autowired
    private CustomerRepository customerRepository;

    @Test
    void anonymousChatWithNoPhoneStaysAnonymous() {
        ChatRequest request = new ChatRequest("chat-anon-" + UUID.randomUUID(), null, "hello");

        ChatResponse response = chatController.chat(request);

        assertThat(response.identityAssurance()).isEqualTo("ANONYMOUS");
        assertThat(response.turnNumber()).isEqualTo(1);
        assertThat(response.text()).isNotBlank();
    }

    @Test
    void chatWithARegisteredPhoneResolvesToPhoneMatched() {
        String phone = "+92300" + String.format("%06d", Math.abs(System.nanoTime() % 1_000_000));
        Customer customer = customerRepository.save(new Customer("Test", "User", "chat.test." + UUID.randomUUID() + "@example.pk", phone));

        ChatRequest request = new ChatRequest("chat-known-" + UUID.randomUUID(), customer.getPhone(), "Where is my latest order?");
        ChatResponse response = chatController.chat(request);

        assertThat(response.identityAssurance()).isEqualTo("PHONE_MATCHED");
    }

    @Test
    void theSameSessionIdAcrossTwoCallsSharesOneSessionAndTurnNumberAdvances() {
        String sessionId = "chat-continuity-" + UUID.randomUUID();

        ChatResponse first = chatController.chat(new ChatRequest(sessionId, null, "hi"));
        ChatResponse second = chatController.chat(new ChatRequest(sessionId, null, "are you there?"));

        assertThat(first.turnNumber()).isEqualTo(1);
        assertThat(second.turnNumber()).isEqualTo(2);
        assertThat(second.sessionId()).isEqualTo(sessionId);
    }

    @Test
    void anOmittedSessionIdIsAutoGeneratedAndReturnedToTheCaller() {
        ChatResponse response = chatController.chat(new ChatRequest(null, null, "hello"));

        assertThat(response.sessionId()).isNotBlank();
    }
}